- 内容: 'Configuring your app icon'
  提示: ''
  翻译: ''
- 内容: 'Add app icon variations to represent your app in places such as Settings, search results, and the App Store.'
  提示: ''
  翻译: ''
- 内容: 'Overview'
  提示: ''
  翻译: ''
- 内容: 'Every app has a distinct app icon that communicates the app’s purpose and makes it easy to recognize throughout the system. Apps require multiple variations of the app icon to look great in different contexts. Xcode can help generate these variations for you using a single high-resolution image, or you can configure your app icon variations by using an app icon’s image set in your project’s asset catalog. visionOS and tvOS app icons are made up of multiple stacked image layers you configure in your project’s asset catalog.'
  提示: ''
  翻译: ''
- 内容: 'Create an app icon'
  提示: ''
  翻译: ''
- 内容: 'When you create your project from a template, it automatically includes a default asset catalog (Assets.xcassets) that contains the AppIcon. If you don’t have a default asset catalog or existing AppIcon or you want to provide an alternate, you can add an app icon to an asset catalog manually:'
  提示: ''
  翻译: ''
- 内容: 'In the Project navigator, select an asset catalog.'
  提示: ''
  翻译: ''
- 内容: 'Click the Add button (+) at the bottom of the outline view.'
  提示: ''
  翻译: ''
- 内容: 'In the pop-up menu, choose OS variant > OS variant App Icon. Xcode creates a new app icon set or image stack with the name AppIcon.'
  提示: ''
  翻译: ''
- 内容: 'Specify app icon variations'
  提示: ''
  翻译: ''
- 内容: 'Variations of your app icon appear throughout the system in places like the Home View, Settings, and search results. In Xcode 14 and later, for iOS, macOS or watchOS apps, you can generate all variations of your icon using a single 1024×1024 pixel image or provide variations for all sizes. Although using a single size is the default behavior for new apps or new icons in the asset catalog, you might need all sizes in order to include detail in larger variants and simplify as app size decreases. If you have an existing project that provides multiple variants, consider providing a single size when that is all your icon requires.'
  提示: ''
  翻译: ''
- 内容: 'For each platform your app supports, choose between using a single size and providing all sizes in the Asset Catalog:'
  提示: ''
  翻译: ''
- 内容: 'In the Project navigator, select an asset catalog.'
  提示: ''
  翻译: ''
- 内容: 'In the Asset Catalog, select the icon.'
  提示: ''
  翻译: ''
- 内容: 'To view and edit attributes, select Inspectors > Attributes from Xcode’s View menu.'
  提示: ''
  翻译: ''
- 内容: 'Select Single Size or All Sizes from the pop-up menu for the platform you want to change.'
  提示: ''
  翻译: ''
- 内容: 'For each platform your app supports, add a single image that Xcode can use to generate your icon variations, or add an image for each icon variation of an icon set in the Asset Catalog:'
  提示: ''
  翻译: ''
- 内容: 'In the Project navigator, select an asset catalog.'
  提示: ''
  翻译: ''
- 内容: 'In the Asset Catalog, select the icon.'
  提示: ''
  翻译: ''
- 内容: 'From the Finder, drag image variations of the app icon to the image wells in the detail area of the Asset Catalog in Xcode that match their resolutions and use cases. visionOS and tvOS app icons combine a stack of multiple image layers to create a sense of depth. For tvOS apps, the asset catalog contains an App Icon & Top Shelf Image folder with the different app icon and launch image sets.'
  提示: ''
  翻译: ''
- 内容: 'For general design guidance, see App icons. For platform-specific design guidance:'
  提示: ''
  翻译: ''
- 内容: 'visionOS'
  提示: ''
  翻译: ''
- 内容: 'iOS'
  提示: ''
  翻译: ''
- 内容: 'macOS'
  提示: ''
  翻译: ''
- 内容: 'tvOS'
  提示: ''
  翻译: ''
- 内容: 'watchOS'
  提示: ''
  翻译: ''
- 内容: 'Configure the layers of an image stack'
  提示: ''
  翻译: ''
- 内容: 'By default, visionOS and tvOS app icons are constructed with three layers. This is the maximum number of layers visionOS icons support but you can use up to five layers when constructing tvOS icons. To add a layer, Click the Add button (+), choose OS variant > OS variant App Icon Layer. To remove a layer, select the layer and click the Remove button (-).'
  提示: ''
  翻译: ''
- 内容: 'Add images to each layer by dragging them from the Finder into the image wells in the detail area of the Asset Catalog in Xcode. For information on the use of layers, see App icons visionOS and tvOS.'
  提示: ''
  翻译: ''
- 内容: 'Note'
  提示: ''
  翻译: ''
- 内容: 'You can use Parallax Previewer app or Parallax Exporter plug-in to create and preview Layer Source Representation (.lsr and .xlsr) files that you can import into your Asset Catalog in Xcode. Save your file in the LSR file format to import a tvOS icon into Xcode, and save in the XLSR file format to import a visionOS icon. Download these from the Apple Design Resources site.'
  提示: ''
  翻译: ''
- 内容: 'Specify an App Store icon'
  提示: ''
  翻译: ''
- 内容: 'If you distribute your app through the App Store, you must provide app icon imagery to use in the App Store. In the Project navigator, select an asset catalog and add icon images to the appropriate image wells in an app icon set or image stack. The App Store image well location varies by platform.'
  提示: ''
  翻译: ''
- 内容: 'Platform'
  提示: ''
  翻译: ''
- 内容: 'App Store icon location'
  提示: ''
  翻译: ''
- 内容: 'iOS'
  提示: ''
  翻译: ''
- 内容: 'Drag an icon image to the iOS 1,024pt image well.'
  提示: ''
  翻译: ''
- 内容: 'iMessage'
  提示: ''
  翻译: ''
- 内容: 'For the iOS target, drag an icon image to the iOS 1,024pt image well in the AppIcon set. For the iMessage Extension target, drag an icon to the Messages App Store image well in the iMessage App Icon set.'
  提示: ''
  翻译: ''
- 内容: 'Sticker Pack'
  提示: ''
  翻译: ''
- 内容: 'Drag an icon image to the iOS 1,024pt image well and the Messages App Store image well.'
  提示: ''
  翻译: ''
- 内容: 'macOS'
  提示: ''
  翻译: ''
- 内容: 'Drag an icon image to the App Store - 2x image well.'
  提示: ''
  翻译: ''
- 内容: 'tvOS'
  提示: ''
  翻译: ''
- 内容: 'Drag images to the image wells for the layers of your App Icon - App Store stack in the App Icon & Top Shelf Image folder. The App Store generates an icon from the layers of the image stack.'
  提示: ''
  翻译: ''
- 内容: 'visionOS'
  提示: ''
  翻译: ''
- 内容: 'Drag images to the image wells for the layers of your visionOS App Icon stack. The App Store generates an icon from the layers of the image stack.'
  提示: ''
  翻译: ''
- 内容: 'watchOS'
  提示: ''
  翻译: ''
- 内容: 'For the iOS target, drag an icon image to the iOS 1,024pt image well. For the WatchKit App target, drag an icon image to the watchOS image well.'
  提示: ''
  翻译: ''
- 内容: 'Change the default app icon set'
  提示: ''
  翻译: ''
- 内容: 'If you don’t create your project from a template, or you want to change your default app icon set, specify which one to use in your target’s build settings.'
  提示: ''
  翻译: ''
- 内容: 'In the Project navigator, select the project and in the project editor, select the target.'
  提示: ''
  翻译: ''
- 内容: 'In the App Icons and Launch Images section of the General pane, choose the app icon set from the App Icons Source pop-up menu.'
  提示: ''
  翻译: ''
- 内容: 'If you don’t select the Include all app icon assets option, Xcode only includes the app icon set you specify in the App Icons Source pop-up menu when it builds your app. You might leave this option unselected if you want to use a different icon for the Debug and Release builds of your app without including the Debug icon in your Release app bundle. You can specialize the app icon for the Debug and Release configurations by modifying the Primary App Icon Set Name build setting in the Build Settings tab.'
  提示: ''
  翻译: ''
- 内容: 'Xcode also includes any additional app icon sets you specify under the Alternate App Icon Sets build setting. Include any icon sets your app can select using setAlternateIconName(_:completionHandler:) or use in App Store product pages.'
  提示: ''
  翻译: ''
- 内容: 'For information on configuring tests that use icons in App Store Connect, see Product Page Optimization.'
  提示: ''
  翻译: ''
